### ISSUE TITLE
create-account's default value for --initialBalance is extremely high

### ISSUE THREAD

**Issue by charleslavon** [near/near-cli#1004]
`initialBalance` is an optional param of significant consequence when it is omitted, a consequence of 100N https://github.com/near/near-cli/blob/4b4a787d0eafaa97fb7c2c741cdfaacf2c53f35b/commands/create-account.js#L34-L38

Recommendation: `initialBalance` should be a required parameter

**Comment by willemneal** [comment]
Currently a lot of tests depend on this default, which while not the reason to keep it, is the reason it hasn't changed.

See https://github.com/near/near-cli/pull/991

**Comment by frol** [comment]
I want to mention that there is a similar issue #238

**Comment by gagdiez** [comment]
the value has been changed to `1N` by default.
