### ISSUE TITLE
Near login does not point to mynearwallet.com

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-cli#1037]
**Describe the bug**
Near login still redirects users too. The old wallet website

**To Reproduce**
Use near CLI in your terminal, then call near login and you get redirected to the wallet

**Expected behavior**
It should send me to mynearwallet.com or give me an option between which website I want

**Desktop (please complete the following information):**
 - MacOS

**Comment by doriancrutcher** [comment]
Update to this. I think we should have the 

```
$ near login
```
command forward users to some sort of wallet selector site

**Comment by gagdiez** [comment]
mynearwallet is the default wallet now
