### ISSUE TITLE
Even when the nodeUrl is changed to a different value, `near` still reports it is accessing testnet

### ISSUE THREAD

**Issue by nagisa** [near/near-cli#1039]
```
#near --nodeUrl https://rpc.mainnet.near.org state chaenomeles.near

Account chaenomeles.near is not found in testnet

Use export NEAR_ENV=mainnet to use mainnet accounts. 
```

Here, the cli is reporting "not found in testnet" even though the tool is already pointed at mainnet via `nodeUrl`. This is potentially quite confusing.

**Comment by gagdiez** [comment]
now the users can correctly select networks using `--networkId`
