### ISSUE TITLE
near view blocks for few seconds

### ISSUE THREAD

**Issue by robert-zaremba** [near/near-cli#1043]
**Describe the bug**

Calling `near view ...` prints a response and blocks for few more seconds before finishing.

**Expected behavior**

After printing response, `near view` should finish immediately.

 - OS: Linux
 - Node: v19.3
 - near-cli: 3.4.2

**Comment by mfornet** [comment]
This is probably related to telemetrics. I have it disabled, and I don't experience this behavior.

**Comment by robert-zaremba** [comment]
thanks, how do you disable it?

**Comment by mfornet** [comment]
Check the file `~/.near-config/settings.json`

**Comment by robert-zaremba** [comment]
Thanks. This works. I will leave this issue open. Documentation should be updated.

**Comment by gagdiez** [comment]
`near-cli` does not include telemetric anymore
