### ISSUE TITLE
NPM Warn For @ledgerhq/hw-transport-u2f

### ISSUE THREAD

**Issue by trechriron** [near/near-cli#1062]
**Describe the bug**
A NPM Warn on install shown for the package @ledgerhq/hw-transport-u2f

**To Reproduce**
1. Run PNPM install (or Yarn, or NPM)

**Expected behavior**
No warnings of deprecated packages are displayed.

**Screenshots**
` deprecated @ledgerhq/hw-transport-u2f@5.36.0-deprecated: @ledgerhq/hw-transport-u2f is deprecated. Please use @ledgerhq/hw-transport-webusb or @ledgerhq/hw-transport-webhid. https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md`

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 12.6

**Additional context**
None.

**Comment by gagdiez** [comment]
`near-cli` no longer supports ledger, please consider migrating to `near-cli-rs`
