### ISSUE TITLE
`near login` no longer works after wallet deprecation

### ISSUE THREAD

**Issue by Wabinab** [near/near-cli#1080]
**Describe the bug**
Since `wallet.near.org` and its testnet equivalent had been deprecated, links generated by `near login` no longer works. 

**To Reproduce**
1. Call `near login`. 
2. It'll open in new browser; but it doesn't show up the authentication page anymore, redirecting to main page instead. 

**Expected behavior**
Suppose allow authentication. 

**Suggested Fix**
Get the link to redirect to another wallet instead, like mynearwallet.com, by replacing `wallet.testnet.near.org` with `testnet.mynearwallet.com` (and its correspondence for mainnet, and other net).

**Comment by LakshyaSatpal** [comment]
I was faced with the same problem. Ready to work on this issue.

**Comment by gagdiez** [comment]
`near-cli v3.5.0` was released, it uses mynearwallet as default, instead of wallet.near.org. Please let us know if you encounter any troubles with it
