### ISSUE TITLE
Incorrect documentation for near deploy

### ISSUE THREAD

**Issue by kavink98** [near/near-cli#1101]
The instructions to deploy a contract provided in the documentation does not work in version 4.0.6

This is how to deploy a contract as per the documentation 
`near deploy --accountId example-contract.testnet --wasmFile out/example.wasm`
But this doesn't work, it appears this is how you deploy the contract now
`near deploy example-contract.testnet out/example.wasm`

**Comment by gagdiez** [comment]
the README is fixed now, thanks for reporting
