### ISSUE TITLE
--force option does not override question to overwrite contract

### ISSUE THREAD

**Issue by wackazong** [near/near-cli#1104]
**Describe the bug**
`near deploy` asks a security question whether to overwrite an existing contract also if `--force true` is used.

**To Reproduce**
`near deploy account new.wasm --initFunction init --initArgs '{"some": "args"}' --force true`

**Expected behavior**
The new wasm should be directly deployed.

**Additional context**
Workaround is to do this
`echo y | near deploy account new.wasm --initFunction init --initArgs '{"some": "args"}'`

**Comment by gagdiez** [comment]
should be fixed in latest release (`4.0.8`) please ping me back if not.
