### ISSUE TITLE
update docs in readme to reflect breaking changes in `4.0.0` release

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-cli#1105]
With `near-cli` `4.0.0` release breaking changes were not documented in this project's README or docs.near.org. 

Community has been reporting issues using certain commands like `near deploy` [See Telegram Chat here](https://t.me/neardev/40134). 

Related: #1101, #1103, #1104

**Comment by mikedotexe** [comment]
So this is quite critical (we're live at ETHDenver and hackathoners are getting blocked) and will take less than 1 hour. Another solution is to yank the major version 4 from NPM so people will automatically install the version that's documented

**Comment by gagdiez** [comment]
Updated readme and fixed https://github.com/near/near-cli/issues/1101, https://github.com/near/near-cli/issues/1104 in the latest release `4.0.8`

I don't understand were people found https://github.com/near/near-cli/issues/1103, will ask the user that reported it

**Comment by gagdiez** [comment]
Closing this since the README was updated
