### ISSUE TITLE
Separate templating functionality from near-shell

### ISSUE THREAD

**Issue by MaksymZavershynskyi** [near/near-cli#144]
As discussed here it seems like there is a wide support of separating templating functionality from near-shell.
 [https://github.com/nearprotocol/near-shell/pull/133#issuecomment-530190550](https://github.com/nearprotocol/near-shell/pull/133#issuecomment-530190550)

**Comment by icerove** [comment]
sorry I didn't receive any notification before and until today I check it myself I will change them and help with seperating

**Comment by icerove** [comment]
So what is going on for separate blank-project template repo?
