### ISSUE TITLE
Improve staking command

### ISSUE THREAD

**Issue by behaviary** [near/near-cli#218]
1.  1.  1.  Currently, in order to stake we run the following command:

```
 near stake <accountId> <pubKey> <amount>
 ```

1.  1.  1.  It would be fantastic to have the following commands:

```
 near stake <amount>
 ```
 For the last account that logged in

AND

```
 near stake <accountId> <amount>
 ```
 For any arbitrary account.

**Comment by frol** [comment]
Note that you still need to provide the public validator key there. It is not the account public key there.

**Comment by bowenwang1996** [comment]
Yeah public key cannot be omitted here.
