### ISSUE TITLE
Login improvement

### ISSUE THREAD

**Issue by behaviary** [near/near-cli#219]
It would be great if when I `login` to the shell, I would not need to be in any specific folder. 

Expected behavior:
 ```
 near login

1.  LOGIN FLOW ONE TIME
     <span class="error">[...]</span>
     cd ~/ && near <do stuff>
2.  It works!
     cd ~/Desktop && near <do stuff>
3.  It works!
     ```

One way to do this is to save the login keys to `/.near/dev/` instead of the local `neardev`. This would require some changes to how apps get/use config.

**Comment by kcole16** [comment]
@vgrichina Thoughts on this? We currently recommend installing shell globally, which makes the folder specific behavior kinda confusing
