### ISSUE TITLE
Remove `dev-account` file in favor of `dev-account.env`

### ISSUE THREAD

**Issue by mikedotexe** [near/near-cli#287]
See pull request here:
 [https://github.com/nearprotocol/near-shell/pull/286](https://github.com/nearprotocol/near-shell/pull/286)

There is a long-term strategy that involves amending our examples (including `create-near-app`) to use cross-platform environment variable tools. This issue is a reminder remove the creation of the `neardev/dev-account` file created during the `dev-deploy` command.

As a rule of thumb (though subject to possibly more repos) this issue can be addressed once all the examples on <span class="error">[awesome-near]</span>([https://github.com/nearprotocol/awesome-near](https://github.com/nearprotocol/awesome-near)) have been modified to use <span class="error">[env-cmd]</span>([https://www.npmjs.com/package/env-cmd](https://www.npmjs.com/package/env-cmd)) as well as <span class="error">[create-near-app]</span>([https://github.com/nearprotocol/create-near-app](https://github.com/nearprotocol/create-near-app)).

**Comment by gagdiez** [comment]
Examples now implement this
