### ISSUE TITLE
Support third party key stores

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#311]
There are various key stores that near shell can support:

*   Mac's Keychain
*   GNU GPG, supports ED25519 and SECP256K1 [https://wiki.gnupg.org/ECC](https://wiki.gnupg.org/ECC)
*   Ledger support

CC @damons

**Comment by volovyks** [comment]
Promising library suggested by @mikedotexe: https://github.com/atom/node-keytar#keytar---node-module-to-manage-system-keychain
