### ISSUE TITLE
Errors shown escaped in command line

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#317]
Errors have escape characters when shown in command line.

1.  Steps to reproduce
     1\. Run some command that will generate a smart contract error
     2\. Observe that error is escaped
     ```
     $ near call delegate-to-me.test new ' {"owner_id": "illia", "staking_public_key": "5j48GQoZyzW7jjeMFAgztUS2Ui5LAn3Kx7KJEXCLz6hv"} 

    ' --account_id delegate-to-me.test
     Error: GuestPanic <span class="error">[Error]</span>: Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error("missing field `owner`", line: 1, column: 88)', src/lib.rs:68:1
     ```

**Comment by june07** [comment]
So the output should be...
Error: GuestPanic [Error]: Smart contract panicked: panicked at &#39;Failed to deserialize input from JSON.: Error("missing field `owner`", line: 1, column: 88)&#39;, src/lib.rs:68:1

?

**Comment by mikedotexe** [comment]
I'm thinking this would be good for @volovyk-s

**Comment by Rishabhraghwendra18** [comment]
Hi . May I work on this ?
