### ISSUE TITLE
Add network key to unencrypted key files

### ISSUE THREAD

**Issue by mikedotexe** [near/near-cli#387]
As mentioned here in the shell NEP:
https://github.com/nearprotocol/NEPs/blob/87463e7a551885ccdcacf9c141881a9cef1968d0/text/0000-near-shell.md#3-key-management

We will be adding a key for `network`. That way it will be simple to determine if an end user is accidentally trying to run a command on testnet with a betanet account.

For keys that do not have this key, we can use logic for the top-level account (or `helperAccount`) as specified from the `NEAR_ENV`/`NODE_ENV`

**Comment by volovyk-s** [comment]
@mikedotexe is it still relevant? We already have the ability to manage network ([docs](https://docs.near.org/docs/tools/near-cli#network-selection)), and we have this option:
https://github.com/near/near-cli/blob/master/bin/near-cli.js#L162

If it's still relevant, can you please show an example of the functionality that we don't have? It's not clear from the issue description.
