### ISSUE TITLE
near login ignores optional flags

### ISSUE THREAD

**Issue by MaksymZavershynskyi** [near/near-cli#394]
```
 near --version
 0.24.1
 ```

`near login --help` specifies that the following flags can be passed to it:
 ```
 --help Show help <span class="error">[boolean]</span>
 --version Show version number <span class="error">[boolean]</span>
 --nodeUrl, --node_url NEAR node URL <span class="error">[string]</span> <span class="error">[default: "http://localhost:3030"]</span>
 --networkId, --network_id NEAR network ID, allows using different keys based on network <span class="error">[string]</span> <span class="error">[default: "default"]</span>
 --helperUrl NEAR contract helper URL <span class="error">[string]</span>
 --keyPath Path to master account key <span class="error">[string]</span>
 --accountId, --account_id Unique identifier for the account <span class="error">[string]</span>
 --useLedgerKey Use Ledger for signing with given HD key path <span class="error">[string]</span> <span class="error">[default: "44'/397'/0'/0'/1'"]</span>
 ```

However when I create project with
 ```
 npx create-near-app --vanilla myproject
 ```
 navigate into it
 ```
 cd myproject
 ```
 and execute
 ```
 near login --networkId betanet
 ```
 It still opens the following wallet URL: [https://wallet.testnet.near.org/create/](https://wallet.testnet.near.org/create/)

Here is `myproject/src/config.js`:
 ```js
 const CONTRACT_NAME = process.env.CONTRACT_NAME ||'myproject';

function getConfig(env) {
 switch (env) {

 case 'production':
 case 'mainnet':
 return 

 { networkId: 'mainnet', nodeUrl: 'https://rpc.mainnet.near.org', contractName: CONTRACT_NAME, walletUrl: 'https://wallet.mainnet.near.org', helperUrl: 'https://helper.mainnet.near.org', } 

;
 case 'development':
 case 'testnet':
 return 

 { networkId: 'default', nodeUrl: 'https://rpc.testnet.near.org', contractName: CONTRACT_NAME, walletUrl: 'https://wallet.testnet.near.org', helperUrl: 'https://helper.testnet.near.org', } 

;
 case 'devnet':
 return 

 { networkId: 'devnet', nodeUrl: 'https://rpc.devnet.near.org', contractName: CONTRACT_NAME, walletUrl: 'https://wallet.devnet.near.org', helperUrl: 'https://helper.devnet.near.org', } 

;
 case 'betanet':
 return 

 { networkId: 'betanet', nodeUrl: 'https://rpc.betanet.near.org', contractName: CONTRACT_NAME, walletUrl: 'https://wallet.betanet.near.org', helperUrl: 'https://helper.betanet.near.org', } 

;
 case 'local':
 return {
 networkId: 'local',
 nodeUrl: 'http://localhost:3030',
 keyPath: `$

 {process.env.HOME} 

/.near/validator_key.json`,
 walletUrl: 'http://localhost:4000/wallet',
 contractName: CONTRACT_NAME,
 };
 case 'test':
 case 'ci':
 return 

 { networkId: 'shared-test', nodeUrl: 'https://rpc.ci-testnet.near.org', contractName: CONTRACT_NAME, masterAccount: 'test.near', } 

;
 case 'ci-betanet':
 return 

 { networkId: 'shared-test-staging', nodeUrl: 'https://rpc.ci-betanet.near.org', contractName: CONTRACT_NAME, masterAccount: 'test.near', } 

;
 default:
 throw Error(`Unconfigured environment '$

 {env} 

'. Can be configured in src/config.js.`);
 }
 }

module.exports = getConfig;
 ```

**Comment by chadoh** [comment]
On line 135, we define `config` https://github.com/near/near-shell/blob/a645203bb6427c66c3a8a06e1c42327c4f80eedc/bin/near-cli.js#L135

This then reads the `src/config.js` from your local project, and passes in `NEAR_ENV` or `NODE_ENV` environment variable https://github.com/near/near-shell/blob/a645203bb6427c66c3a8a06e1c42327c4f80eedc/get-config.js#L3-L7

Seems like we should read the `networkId` option before we define `config`, and pass it into that `getConfig` definition. If set, it should take precedence over `NEAR_ENV` / `NODE_ENV`

**Comment by thisisjoshford** [comment]
> I'd say timebox this to half a day, or a full day at most, please. We can let people know the way to do this is:
> `NEAR_ENV=betanet near login`

@mikedotexe I chatted with @mehtaphysical a bit about this yesterday and need guidance on the best way to move forward. Ideally I think `--networkId` should do what users expect and change the network for the command. This would be a breaking change and require a bit of refactoring. Either way we move forward we still would need to rename this command to something that makes it clear to the user what its intended purpose is (specifying credential folder location). `--keyFolder` or `--keyDirectory` perhaps... but we have `--keyPath` currently which is a different function and may be confusing to users which one to use and for what use case.
