### ISSUE TITLE
Generate-key does not pickup NEAR_ENV when creating a key for TestNet

### ISSUE THREAD

**Issue by htafolla** [near/near-cli#470]
When creating a new key for testnet it stored the key in the `default` folder instead of the `testnet` folder even when NEAR_ENV=testnet

If I use the parameter --networkId testnet

Does the folder a key is associated with in .near-credentials matter? I'm not sure if it has to be associated with the correct network to work properly.

**Comment by vgrichina** [comment]
for historical reasons testnet uses `default` `networkId` https://github.com/near/near-cli/blob/c6870c5f30799cb8cdcdc55046edba792d37daa6/config.js#L20
