### ISSUE TITLE
Show version when running near 

### ISSUE THREAD

**Issue by AnaisUrlichs** [near/near-cli#484]
***Is your feature request related to a problem? Please describe.***
 It is quite difficult to know when I should be upgrading my version of near shell. Specifically, when I run near-shell, it does not display the current version. In the case of, for example, npm, it would suggest me to update my current version if there is a new release.

***Describe the solution you'd like***
 Display at the beginning of the command list the current version.

***Describe alternatives you've considered***
 Not sure what other options there are to tell dev they are running an outdated version ![](/images/icons/emoticons/biggrin.png)

***Additional context***
 This is currently how it looks
 !<span class="error">[Screenshot from 2020-08-04 10-30-44]</span>([https://user-images.githubusercontent.com/33576047/89272558-9e472300-d63e-11ea-8489-8fb0adafd4a9.png](https://user-images.githubusercontent.com/33576047/89272558-9e472300-d63e-11ea-8489-8fb0adafd4a9.png))

**Comment by june07** [comment]
Or maybe add a --version flag.  I've actually mentioned this previously somewhere.
