### ISSUE TITLE
Interactive prompts when arguments omitted

### ISSUE THREAD

**Issue by chadoh** [near/near-cli#486]
***Is your feature request related to a problem? Please describe.***
 When deploying contracts or making other complex calls with `near-cli`, remembering all of the arguments required can be cumbersome.

***Describe the solution you'd like***
 Open Zeppelin has a nice CLI pattern they use that I think would benefit near-cli: by default, when you run a command like `openzeppelin deploy`, if you don't provide any arguments, it has an interactive prompt to walk you through your choices.

***Describe alternatives you've considered***
 ...

***Additional context***
 !<span class="error">[openzeppelin deploy cli]</span>([https://user-images.githubusercontent.com/221614/89350975-0a497b80-d67f-11ea-8555-8d538c8f0900.gif](https://user-images.githubusercontent.com/221614/89350975-0a497b80-d67f-11ea-8555-8d538c8f0900.gif))

**Comment by june07** [comment]
Other thoughts on this...?
