### ISSUE TITLE
`near delete` with positional arguments is dangerous

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-cli#509]
***Is your feature request related to a problem? Please describe.***

Current API supports the following:

```bash
 near delete <accountId> <beneficiaryId>
 ```

It's really easy to mess up the arguments and delete the `beneficiaryId` account instead of `accountId`.

***Describe the solution you'd like***

There are 2 possible solutions:

*   Confirm each request. This should be on by default and overridden with `-y`. This way the shell will first display the action you want to do and then ask you to confirm it. Will prevent accidental mistakes.
*   Make account ID and beneficiary ID named required arguments instead of positional.

**Comment by gagdiez** [comment]
The new version needs confirmation before continuing, and shows a explicit message with which account is being deleted and which is beneficiary
