### ISSUE TITLE
Show informative error when account is not found

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#530]
It's very common that querying wrong network (e.g. testnet is default but want mainnet).

Currently error is "[-32000] Server error: ..." with huge stack trace.

Instead should show error saying:
```
Account <account_id> is not found in <network_id> network.
```

Also if prefix on the account is `.near` show: `Use export NEAR_ENV=mainnet to use MainNet accounts`, if `.testnet` or `.betanet` same.

**Comment by mikedotexe** [comment]
Sounds good, I think we were holding out hope that errors might return typed errors or special error numbers, but we can definitely look at the error message and use regex/string parsing to determine what to tell the user.

**Comment by rozum-dev** [comment]
hey @mikedotexe can you pls check my pr https://github.com/near/near-cli/pull/532
on this issue

**Comment by volovyk-s** [comment]
@ilblackdragon @mikedotexe Looks like this issue can be closed.
We have merged code from @rozum-dev + some aditional changes from me. Final version can be foud in this PR: https://github.com/near/near-cli/pull/602/files
