### ISSUE TITLE
Run transaction in dry mode first

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#561]
With MainNet life, it's really bad to have failed transactions because we have wrong arguments or something else.

General solution is to have a dry mode, when transaction is executed in "view only" and everything is validated.

Caveats: nearcore fails right now because of deposit / sender are missing in view mode.
 We may want to modify that with additional flags to support this.

**Comment by bowenwang1996** [comment]
Should also consider how to prevent abuse because you can easily do some expensive stuff with function calls.
