### ISSUE TITLE
`near generateKey key --useLedgerKey` confirmation is cumbersome

### ISSUE THREAD

**Issue by djsatok** [near/near-cli#567]
**Use case**
A user wants to generate public key with specific HD Path with `near generate-key key --useLedgerKey="44'/397'/0'/0'/2'"`. `near-cli` returns that the user need to confirm the key on the device. After confirming the key is displayed in the CLI.

**A problem**
The confirmation is cumbersome for the user. He doesn't know what he is confirming. A key depicted in the device doesn't match with anything that a user has in front of him at the moment of the confirmation. Also, after the confirmation, there's no guarantee for the user, that the displayed in CLI public key is actually the one that was provided in the device (a single character changed will result in a loss of the tokens).
**Note**: When one uses Ledger to send Bitcoin, the Ledger provides a meaningful message: "Do you want to send 0.1 BTC to the address: 1sdasDtdgk1238a..."? Yes / No. During this process a user can verify the address that he entered through the Ledger Live interface.

**Current workaround scheme**
To generate the key 2 times. First one is just for the displaying it to the console. Second -- to check, whether the key on the device matches the one that is displayed in the console.

**Proposed solution**
To store the generated keys in the local storage (for example, `~/.near/keys`) in a map with HD Path as a key. During the first call of `near generate-key key --useLedgerKey="44'/397'/0'/0'/2'"`, a message should be displayed: 'This key was never generated before, please confirm on Ledger the copying of the key to the local storage'. Once the this confirmation is done by user, one should display the key in the CLI and send additional message to CLI: 'Please confirm that this key is the one that is displayed in Ledger'. After this additional call of `async getPublicKey` is performed, and a user need to approve the match of the keys. If the confirmation was successful, the key is stored to the local storage; if not -- nothing happens.

After the first key creation, a user for sure would like to access his public key to send/receive tokens, state his key in some contracts or just find his account in the explorer. The safe way to do this is once again generate the key in Ledger. However, by this time we already have a key in the local storage, so we can do the generation with only one confirmation: display the key in the CLI and then ask the user to verify the key with the one that is displayed in Ledger. In case of a success, nothing additional happens. In case of failure, this means that the user is using the Ledger with different initialisation OR the local storage was modified, this warning along with the directions of the local storage key management (update the stored key?) should appear.

**De-anonymising risk**
Storing all generated public keys in a local storage, exposes a user to a risk of de-anonymising his accounts. If the computer is hacked, the hacker is able to read the storage and figure out the split of tokens in between different user accounts.

**Note**: Ledger Live is able to track the transactions in officially supported blockchains even without the device. This means that it stores the public keys somewhere, which leads to the same risk.

The risk can be delegated to the user: we can propose an option to store the keys for the convenience in the local store, or to switch off this functionality to enhance the anonymity. This can be done through `near configure --storePublicKeys=true`

**Additional consideration**
In addition to the above, one can introduce meaningful messages in the Near App in Ledger. For example during the first key generation operation, two confirmations are be required: first -- `Do you want near-cli to get the pub key from HD Path "44'/397'/0'/0'/2'"`, second -- `Check whether the pubkey displayed in the CLI is 1sdasDtdgk1238a...`. However, this might be more complicated due to Ledger checks.

**Comment by volovyk-s** [comment]
@mikedotexe @djsatok 
Please, check the attached PR. There is an example in the description. Now it's possible to compare PK on Ledger with the one that was printed to the terminal.
I think that saving the public key permanently will add lots of difficulties and potential dangers. At the same time, the only benefit is that starting from the second attempt to get the key we will have to approve it on the ledger once, instead of twice.
