### ISSUE TITLE
Quickie: Language is unclear when asking permission of me on CLI

### ISSUE THREAD

**Issue by eriktrautman** [near/near-cli#595]
I went to run the following command just now and received the following message on the CLI:

```
 $ near keys foo.near
 We would like to help with your development journey with NEAR. We will ask you to share your account Id while using command. Would you like to share the account Id (y/n)? n
 ```
 This message isn't sufficient for me to understand what you're asking and why. "We will ask you to share your account Id while using command" doesn't make sense, both because the English isn't quite right and the context is missing. If I'm going to agree to something on the CLI, I need to know:
 1\. What are you actually asking?
 2\. What is the scope of what you're asking? eg is this one-time or only when I use X commands or anything or...?
 3\. What are the risks of what you're asking? give me the info I need to make an informed decision (or link out to something in docs if not enough space).
 4\. What are the beneifts of what you're asking? you say you want to help me but how is that actually happening? Like I'm helping the project overall by feeding my data or you're planning to reach out to me directly (which I definitely don't care about)?
 4\. How can I undo my decision once it has been made?

Unless all of those are met, I will never say yes and expect others won't too. Recommend to flesh this request out further so this is done.

**Comment by thisisjoshford** [comment]
Was not able to reproduce this and didn't find anything in the codebase that matches the copy below:

```bash
$ near keys foo.near
We would like to help with your development journey with NEAR. We will ask you to share your account Id while using command.  Would you like to share the account Id (y/n)? n
```

However, I did find "getting event tracking consent" which most likely replaced the message @eriktrautman received when this issue was originally created.

```js
const getEventTrackingConsent = async () => {
    return askYesNoQuestion(
        chalk`Please help us to collect data on near-cli usage to improve developer experience. ` +
        chalk`\nWe will never send private information. We collect which commands are run with attributes and your account ID.` +
        chalk`\nNote that your account ID and all associated on-chain transactions are already being recorded on public blockchain. ` +
        chalk`\n\n{bold.yellow Would you like to opt in (y/n)? }`);
};
```

I believe this better answers the five questions above aside from how to opt out after opting in. I will see if I can find a solution to question #5 and can also wordsmith the tracking consent question a little if you like @mikedotexe.

**Comment by thisisjoshford** [comment]
So I believe we can write this feature into `near-cli` according to [mixpanel docs](https://developer.mixpanel.com/docs/javascript#opting-users-out-of-tracking). Would you like this to be done @mikedotexe?
