### ISSUE TITLE
Add gas and amount flags for evm calls

### ISSUE THREAD

**Issue by mikedotexe** [near/near-cli#604]
Take a look at `evm-view` and `evm-call` commands, and add ability to attach deposit and gas.
And update:
https://docs.near.org/docs/development/near-cli#near-evm-call

**Comment by djsatok** [comment]
Please raise the priority to this one.

**Comment by volovyk-s** [comment]
@djsatok `EVM` functionality is deprecated in `near-cli`.
https://github.com/near/near-cli/blob/master/commands/evm-call.js#L34
https://github.com/near/near-cli/blob/master/commands/evm-view.js#L21

This issue is stale. can you please elaborate?

**Comment by djsatok** [comment]
Oh, I missed that. I mean we need to update the docs for the ordinary NEAR calls

**Comment by volovyk-s** [comment]
Ok, I'm closing this one then,
I'm not following what do you want to fix. Docs, or code? Can please specify places in docs or a command that you want to fix?

**Comment by djsatok** [comment]
@volovyk-s  https://github.com/near/near-cli/issues/840
