### ISSUE TITLE
Format near state command

### ISSUE THREAD

**Issue by thor314** [near/near-cli#647]
***Describe the bug***

Currently `near state` command outputs raw JSON from RPC. It's unclear which units are used for what and not very user friendly for developer.
 Eg:
 ```
 $ near state 1.m17.testnet
 Account 1.m17.testnet

 { amount: '200000049344305458300000000', locked: '0', code_hash: 'HvTJeCkG89XdvPTiidYbdkMNZPxhfrdodqQW1Hmz7Zm9', storage_usage: 1997629, storage_paid_at: 0, block_height: 32295698, block_hash: 'E1L7x11pnFpz9nWcYqa83RcdnEMJwWhKuYVg3dWQaZ77', formattedAmount: '200.0000493443054583' } 

```

Better:
 ```
 Account 1.m17.testnet at block 32295698 ([https://explorer.testnet.near.org/blocks/E1L7x11pnFpz9nWcYqa83RcdnEMJwWhKuYVg3dWQaZ77](https://explorer.testnet.near.org/blocks/E1L7x11pnFpz9nWcYqa83RcdnEMJwWhKuYVg3dWQaZ77))
 amount: 200.0000493443054583 N
 locked: 0
 storage: 1.9M (1997629 bytes)
 code_hash: 'HvTJeCkG89XdvPTiidYbdkMNZPxhfrdodqQW1Hmz7Zm9'

For more details see [https://explorer.testnet.near.org/accounts/1.m17.testnet](https://explorer.testnet.near.org/accounts/1.m17.testnet)
 ```

**Comment by anikashc** [comment]
Hey. I would like to give this a shot.

**Comment by anikashc** [comment]
I have found 2-3 files which are related to this. Can you point to the accurate file where this output is being generated after state with <account_id> is called

**Comment by Rishabhraghwendra18** [comment]
Hi 😃 . First timer here . Is anyone working on this issue ?

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18 let's fix it! Please, check if it's reproducable and improve the output. I believe that we can make it even better then the one in the example :)

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s . I had cloned the repo and installed all the node modules using `npm install` but how to run the code , like there is `npm start` to start the development server something like this ?

**Comment by volovyk-s** [comment]
It's a command-line tool, so there is no need to run any servers. Follow this steps:
- `git clone <repo>`
- `cd near-cli`
- `yarn` (it's just simpler,  try to use it :) )
- `./bin/near <commands> <flags>`
- change code, you don't need to build anything
- run `./bin/near <commands> <flags>` again to test your changes 

You can read about near-cli here: https://docs.near.org/docs/tools/near-cli#overview

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s thanks alot

**Comment by Rishabhraghwendra18** [comment]
> @Rishabhraghwendra18 let's fix it! Please, check if it's reproducable and improve the output. I believe that we can make it even better then the one in the example :)
@volovyk-s This issue is reproducable . What will be our next step ?

**Comment by volovyk-s** [comment]
We should show the same information, but format it better. I would say that the plan is:
1. Don't show it as a raw JSON
2. Highlight some words to make it more readable, like **amount:** 10
3. Add units, so it should be:
**amount:** 200000049344305458300000000 **yN**
instead of
amount: '200000049344305458300000000',
4. Add links to explorer, as @thor314 showed in his `Better` section.
5. Feeld free to add other improvements, there is no `perfect` solution to this problem.
