### ISSUE TITLE
Deploy contract has incorrect and unhelpful error messages

### ISSUE THREAD

**Issue by thor314** [near/near-cli#648]
**Describe the bug**
Deploying contracts has incorrect error messages.

Currently, deploying with too little to cover storage includes this error message
`message: "The account 2.m17.testnet wouldn't have enough balance to cover storage, required to have 49762900000000000000000000"`

What is actually meant:
The account 2.m17.testnet wouldn't have enough balance to cover storage, required to have 49762900000000000000000000 **more** NEAR

What would be best:
That wasm blob requires {} NEAR to cover storage. Increase the deposit by {} NEAR with the --amount X command line option.
The account {} wouldn't have enough balance to cover storage, required to have 49762900000000000000000000 more NEAR"

**Comment by Rishabhraghwendra18** [comment]
Hi 😃 . First timer this side . May I fix this bug ?

**Comment by volovyk-s** [comment]
Hey @Rishabhraghwendra18 ! Please, check if it's still reproducible and if yes - where this string is coming from? Is it a part of `near-cli`, `near-api-js` or it's coming from `near-core`. Thanks!

**Comment by khorolets** [comment]
@Rishabhraghwendra18 I believe you can check that is't not reproducible anymore, at least from what I can gather https://github.com/near/near-api-js/blob/ca4aecbfc0b4427bf6e292db6e43e19194e0fa6d/lib/res/error_messages.json#L39

/cc @volovyk-s

**Comment by volovyk-s** [comment]
Thanks, @khorolets ! Closing this issue.
