### ISSUE TITLE
remove dependence on web3.js

### ISSUE THREAD

**Issue by chadoh** [near/near-cli#675]
See https://github.com/near/near-ops/issues/380

near-cli is dual-licensed under MIT & Apache 2.0. Web3.js is licensed as LGPL 3, and is thus incompatible with this project.

Can we switch to [ethers.js](https://github.com/ethers-io/ethers.js/)?

**Comment by mikedotexe** [comment]
Can be helpful
https://docs.ethers.io/v5/single-page/#/v5/migration/web3/
