### ISSUE TITLE
Not possible to add function access key with multiple method names

### ISSUE THREAD

**Issue by nearmax** [near/near-cli#686]
`--method-names` argument in `near add-key` command does not work correctly, because it interprets anything passed to it as a single method name, even if it is separated with commas. This happens because here we always read `--method-names` argument as a single string: https://github.com/near/near-cli/blob/master/commands/add-key.js#L39 and therefore this condition is never false https://github.com/near/near-api-js/blob/master/src/account.ts#L294

**Comment by nearmax** [comment]
I had to hack it by patching my local `node_modules/near-cli/commands/add-key.js` to use `JSON.parse(options.methodNames)`

**Comment by vgrichina** [comment]
> I had to hack it by patching my local `node_modules/near-cli/commands/add-key.js` to use `JSON.parse(options.methodNames)`

why no PR then? :)

though I think parsing JSON not required, should be enough to just split on commas specifically:
https://github.com/near/near-cli/pull/688

**Comment by vgrichina** [comment]
BTW also note that if you need anything custom there is always `near repl`

you can do `near repl --masterAccount youraccount.near`

and then just have JS REPL with stuff setup:

> await account.addKey(...); 

works pretty well if you want to do something one off

**Comment by nearmax** [comment]
> > I had to hack it by patching my local `node_modules/near-cli/commands/add-key.js` to use `JSON.parse(options.methodNames)`
> 
> why no PR then? :)
> 
> though I think parsing JSON not required, should be enough to just split on commas specifically:
> #688

Cause there needs to be more logic that checks whether it has commas or somesuch.

**Comment by mikedotexe** [comment]
I'm talking to Serhii or possibly Chad about being assigned to this issue.
