### ISSUE TITLE
Account removal should not remove the key from credentials

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#692]
Credentials are way too important to be removed by this command.
Potentially, they can be renamed into some <filename>.bak file, but they def should not be deleted.

**Comment by mikedotexe** [comment]
Adding this to project board for tooling

**Comment by thisisjoshford** [comment]
Are you refering to `near delete` @ilblackdragon @mikedotexe? I'm not seeing where credentials are being deleted locally with [this command](https://github.com/near/near-cli/blob/d621481bda66c6056d1577054baaa2f4aac9f37c/index.js#L190-L199). I also tested this manually and the `.json` credentials file for the deleted account was not removed from my local machine.

**Comment by mikedotexe** [comment]
Yeah I think there must have been a mix-up. This isn't the behavior looking at the `delete` command and the code behind it. Just to make sure tested it out, too. Going to close as invalid.

<img width="1021" alt="Screen Shot 2021-05-05 at 5 36 10 PM" src="https://user-images.githubusercontent.com/1042667/117225994-7dc41900-adc8-11eb-8e0f-68c272e4fc26.png">
