### ISSUE TITLE
Remove EVM commands

### ISSUE THREAD

**Issue by frankbraun** [near/near-cli#706]
The EVM commands `near evm-view`, `near evm-call`, and `near evm-init-dev` have been obsoleted by the [Aurora Engine CLI](https://github.com/aurora-is-near/aurora-cli) and should be removed at some point.

@artob

**Comment by mikedotexe** [comment]
Can I help out here, @thisisjoshford ?

**Comment by mikedotexe** [comment]
I think we'll need to sweep the docs to make sure we don't say "yeah you can use NEAR CLI with the EVM"
