### ISSUE TITLE
Publish NEAR CLI

### ISSUE THREAD

**Issue by mikedotexe** [near/near-cli#738]
Josh pointed out it's been a while since NEAR CLI has been updated to NPM. In the future, please just do this.
Use `np` like the instructions here:
https://www.notion.so/nearprotocol/Applayer-release-process-27ae5d35e1f44eb5b83184f100bf84f1#a27e6deb8f3f4a5187671cd1249e7f49

Make sure to reference https://semver.org and make the appropriate bump. Ping people if there are questions.

I tagged three of you, please figure out amongst yourselves who will pull the trigger.

**Comment by mikedotexe** [comment]
Let's do this after #696 is merged, please.

**Comment by volovyk-s** [comment]
Done
