### ISSUE TITLE
Allow to specify amounts in yN

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#751]
New standards like FT now require to attach 1 yN. Currently if user specifies `--amount 1` it will attach 1N.
Let's add support for specifying `1yN` as an amount as well.

**Comment by mikedotexe** [comment]
I'd add to add more color to this as it's a great issue for the upcoming bootcamp.

This will be a good file to start:
`commands/call.js`

To test a command locally… Clone the repo, and then you can run:

    ./bin/near call …

There's a great documentation page covering all the commands with handy copy-pastable examples here:
https://docs.near.org/docs/tools/near-cli

Note that by default, the **testnet** network will be used with the CLI.

**Comment by mikedotexe** [comment]
Since we recently decided to use `deposit` instead of `amount` we would like this to be `depositYocto` instead of `yN` 🙏🏼 
`near call … --depositYocto 2350000000000000000000`
