### ISSUE TITLE
Segmentation fault when running near generate-key with ledger

### ISSUE THREAD

**Issue by gonta71** [near/near-cli#758]
***Describe the bug***
 Run near-cli 2.0 on linux to generate key. Implicit account and public key are shown, but then there is an immediate segfault.

The backtrace shows the following:
 0x0000555555ad2589 in napi_delete_reference ()
 (gdb) bt
 #0 0x0000555555ad2589 in napi_delete_reference ()
 #1 0x00007ffff7108697 in __run_exit_handlers () from /usr/lib/libc.so.6
 #2 0x00007ffff710883e in exit () from /usr/lib/libc.so.6
 #3 0x00007ffff70f0b2c in __libc_start_main () from /usr/lib/libc.so.6
 #4 0x0000555555a759ae in _start ()
 (gdb) 

***To Reproduce***
 > near generate-key ---useLedgerKey
 Witness segfault

***Expected behavior***
 Just show the implicit account and public key and no segfault.

***Desktop (please complete the following information):***

*   OS: Linux
*   Version nodejs 14.16.0

**Comment by Rishabhraghwendra18** [comment]
@gonta71 do I need a hardware ledger to reproduce it ?

**Comment by nagisa** [comment]
I can reproduce this issue as well. So far I was able to encounter this with hardware ledger only.
