### ISSUE TITLE
Don't use deprecated functions in `near-cli`

### ISSUE THREAD

**Issue by volovyk-s** [near/near-cli#760]
We are still using some functions from `near-api-js` that are already deprecated. Such as `signAndSendTransactions` and `functionCall`. It's easy to reproduce by running `yarn test`.

**Comment by Rishabhraghwendra18** [comment]
Hi smiley . First timer this side . May I work on this issue ?

**Comment by volovyk-s** [comment]
> Hi smiley . First timer this side . May I work on this issue ?

Sure. Feel free to create PR.

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s please assign it to me

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s do community have a discord/slack server ?

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18 there is a Discord community: https://discord.com/invite/UY9Xf2k
Are you planning to work on this issue? We need to close it this week.

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s Ya. Please give me this week . I want to solve this issue

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s may you guide me on how to solve this issue ? whether I have to replace deprecated functions with something new or something else ?

**Comment by thisisjoshford** [comment]
Hey @Rishabhraghwendra18 ! The function call part of this issue was solved by a PR I just submitted (#781). My apologies for not thoroughly searching the issues to see if this was already being worked on. Let me know if you still plan on working on a fix for the other deprecated method (you can follow the same solution pattern in the PR I linked above).

**Comment by Rishabhraghwendra18** [comment]
@thisisjoshford Np . I still want to work on bugs or other good first issues .

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18 great! you can check other issues and choose. Issues marked with `low-hanging-fruite` should be a good place to start. If you will have questions - ask them in our [Discord](https://discord.com/invite/UY9Xf2k).

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s I have commented on some low-hanging-fruite issues of this repo. These issues are open for a 1 year and may be is inactive . May you please tell me whether these issues are resolved or not ?

**Comment by volovyk-s** [comment]
@Rishabhraghwendra18 this issue is still open.
Run `yarn test | grep deprecated` and see that there is one deprecated function left. It's `Account.signAndSendTransaction`.
Please, see this PR to understand how this can be fixed.
https://github.com/near/near-cli/pull/782/files

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s do I have to install yarn to run `yarn test | grep deprecated` or I can use npm instead ?

**Comment by volovyk-s** [comment]
> @volovyk-s do I have to install yarn to run `yarn test | grep deprecated` or I can use npm instead ?

You can use npm

**Comment by Rishabhraghwendra18** [comment]
@volovyk-s  I have made the PR . Please review it
