### ISSUE TITLE
Not ignored files in `neardev` fodler

### ISSUE THREAD

**Issue by volovyk-s** [near/near-cli#761]
Each time we run `yarn test` files in `neardev` folder get updated. I'm not sure if they should be ignored, or we should not generate new `acc` each time we run tests.

**Comment by volovyk-s** [comment]
@mehtaphysical maybe you now the reason

**Comment by mehtaphysical** [comment]
That is no good. I'll take a look at this. I'm guessing somewhere in the test we are storing keys
