### ISSUE TITLE
`near call` is using deprecated `functionCall` method

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-cli#781]
`near call` is currently using deprecated version of `account.functionCall` method that uses positional arguments. We should update this in `near-cli` that passes an object for args.

**Comment by volovyk-s** [comment]
related to https://github.com/near/near-cli/issues/760#issuecomment-852195475

**Comment by thisisjoshford** [comment]
> related to [#760 (comment)](https://github.com/near/near-cli/issues/760#issuecomment-852195475)

ahh nice, was submitting this based on an issue raised in our telegram dev support channel. Didn't see that this was already created. Thanks @volovyk-s !
