### ISSUE TITLE
view-state fails without --finality flag

### ISSUE THREAD

**Issue by volovyk-s** [near/near-cli#787]
**Describe the bug**
view-state fails without --finality flag

**To Reproduce**
`near view-state <accId>`

**Expected behavior**
Should clarify that finality is required

**Comment by chadoh** [comment]
I'd prefer we default to `--finality final`, rather than always require it.

Are there other commands that currently require this flag?

**Comment by volovyk-s** [comment]
@chadoh no, this is the only one
It can not be a default parameter because it is in conflict with `blockId`.
