### ISSUE TITLE
near view-state output is not usable

### ISSUE THREAD

**Issue by volovyk-s** [near/near-cli#788]
Output from `near view-state` example:
```bash
[
  {
    key: <Buffer 53 54 41 54 45>,
    value: <Buffer 01 00 00 00 21 00 00 00 00 0c 43 02 53 aa 4a 1d 32 01 ab 59 7a c7 76 9f 73 b4 6c 5f 58 ff 13 41 a5 a1 91 2e ab 4b 07 65 d3 01 21 00 00 00 00 33 70 df ... 63 more bytes>
  }
]
```

Output from HTTPie:
```bash
{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "5cXxUJKUK1DsKzQioSm2DiWiVYg6BzyhZ7W1DKcH1aCf",
        "block_height": 50406189,
        "proof": [],
        "values": [
            {
                "key": "U1RBVEU=",
                "proof": [],
                "value": "AQAAACEAAAAADEMCU6pKHTIBq1l6x3afc7RsX1j/E0GloZEuq0sHZdMBIQAAAAAzcN+6WNBLw2kdWy7Vb32BMxC7t/1wiq7Z4F5/YuOncAAAAKHtzM4bwtMAAAAAAAAOAAAAc2VyaGlpLnRlc3RuZXQ="
            }
        ]
    }
}
```

**Comment by ailisp** [comment]
I'm doing some scripting with near-cli, seems this can be fixed by : `map(kv => {key: kv.key.toString('base64'), value: kv.value.toString('base64')})`

**Comment by volovyk-s** [comment]
> I'm doing some scripting with near-cli, seems this can be fixed by : `map(kv => {key: kv.key.toString('base64'), value: kv.value.toString('base64')})`

Yes, it should do the trick! Can you please create PR?

**Comment by ailisp** [comment]
> Yes, it should do the trick! Can you please create PR?

Sure! https://github.com/near/near-cli/pull/798

> What kind of scripting? Do you think we should keep both encoded and decoded state?

https://github.com/near/repro-near-funcall, the purpose is to download state from testnet and load in a local node, so user can replay/simulate testnet transaction locally
