### ISSUE TITLE
Confusion with contractName argument

### ISSUE THREAD

**Issue by mfornet** [near/near-cli#793]
***Is your feature request related to a problem? Please describe.***

To make a view call from the cli, it asks for `contractName` as one of the arguments.

```
 ❯ near view --help
 near view <contractName> <methodName> <span class="error">[args]</span>
 ```

It is confusing that it refers to the account id where the contract was deployed, vs the actual name of the contract in the implementation.

***Describe the solution you'd like***
 Rename this argument with `contractAccountId`.

***Describe alternatives you've considered***

***Additional context***
 Inspired by this comment in SO:
 [https://stackoverflow.com/questions/67953918/how-can-i-solve-the-error-of-smart-contract/67955563#comment120112679_67955563](https://stackoverflow.com/questions/67953918/how-can-i-solve-the-error-of-smart-contract/67955563#comment120112679_67955563)

**Comment by flmel** [comment]
Hey! The same thing persists in other parts of the CLI If you think we shall rename contractName to contractAccountId in general (which makes sense and would clear confusion for newcommers) let me know I can put a pr.
