### ISSUE TITLE
feat: near dev deploy improve CI friendliness

### ISSUE THREAD

**Issue by zcstarr** [near/near-cli#796]
I'm adding near dev deploy as a ci step. The way near dev deploy is setup at the moment has an event tracking prompt that can't be avoided the first time you run it. This prompt can hang ci unless you redirect some input into stdin. This can get a bit hairy as the context changes.

[https://github.com/near/near-cli/blob/90ca53c8ffcd1fdac7b327fb5a6afcfdc6dc58b1/commands/dev-deploy.js#L42](https://github.com/near/near-cli/blob/90ca53c8ffcd1fdac7b327fb5a6afcfdc6dc58b1/commands/dev-deploy.js#L42)

How do people feel about bubbling up the consent option as an optional arg. I know this gets weird when you save the state in shell settings. The arg would be more of an override you use the arg vs use what's in shell settings?

**Comment by maxhr** [comment]
Bumping this, as it breaks my CI too.

**Comment by idea404** [comment]
Bump as I'd like to run a CI that tests tutorial commands and this is a blocker. I would propose changing this to a notification that does not require user input which defaults at "no" for sharing usage data and can be thus changed at a later time.

**Comment by angshumanHalder** [comment]
Did you guys find any workaround to this? I was trying to dockerize my app and stuck in the deploy phase as the cli doesn't take any default input for tracking, the build process is failing.

**Comment by idea404** [comment]
@angshumanHalder you can pass the 'y' command: `printf 'y\n'` | near dev-deploy

**Comment by angshumanHalder** [comment]
@idea404 thanks. I am able to automate the deploy and build processes. 😄
