### ISSUE TITLE
NEAR CLI failing for NodeJS v13.6

### ISSUE THREAD

**Issue by gokulsan** [near/near-cli#811]
**Describe the bug**
NEAR CLI not working on Ubuntu 21.4 with NodeJS 13.6

**To Reproduce**
1. Go to '...' Ubuntu Terminal
2. Click on '....' Type near --version
3. Scroll down to '....' See the error

**Expected behavior**
NEAR CLI should demonstrate the version value

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version : 21.4

**Comment by mikedotexe** [comment]
Thank you for reporting!

**Comment by mikedotexe** [comment]
With some discussion, it seems that odd version may be different than even. If we can support this, let's fix it, if not, a better error instructing the user: https://nodejs.org/en/about/releases/

**Comment by volovyk-s** [comment]
node version 13.0 -> 13.6 are affected
default node 13 version is 13.14.0

Error is:
`internal/modules/cjs/loader.js:463
  throw e;
  ^
Error: Package exports for '/home/serhii/.fnm/node-versions/v12.20.0/installation/lib/node_modules/near-cli/node_modules/mustache' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/serhii/.fnm/node-versions/v12.20.0/installation/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10) {
  code: 'MODULE_NOT_FOUND'
}`

**Comment by volovyk-s** [comment]
Looks like the fix was added in this commit: https://github.com/nodejs/node/commit/cb27c2bd3ea5cc61e5eba7c6a43a49d3914dfdd1

**Comment by mikedotexe** [comment]
> Looks like the fix was added in this commit: [nodejs/node@cb27c2b](https://github.com/nodejs/node/commit/cb27c2bd3ea5cc61e5eba7c6a43a49d3914dfdd1)
> 
> Since it was a problem with the `node` itself, I would say that we can close this issue and recommend everybody to use 13.7+ instead of 13.6.

Thank you for the details research, Serhii! And thanks for reporting @gokulsan . I believe we can close this

**Comment by MaximusHaximus** [comment]
Might be a good idea to define `engines` if we know that some versions of node don't work for CLI? https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

**Comment by volovyk-s** [comment]
> Might be a good idea to define `engines` if we know that some versions of node don't work for CLI? https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

Looks like we can not exclude `node` versions: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines
Only one range is allowed.

**Comment by MaximusHaximus** [comment]
> > Might be a good idea to define `engines` if we know that some versions of node don't work for CLI? https://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html
> 
> Looks like we can not exclude `node` versions: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines
> Only one range is allowed.

I believe that it defers to standard `semver` matching -- which allows `range1 || range2 || range3`  etc, just like `dependencies` (https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies)
