### ISSUE TITLE
No working with asdf M1

### ISSUE THREAD

**Issue by ingscjoshua** [near/near-cli#848]
**Describe the bug**
after using ``` npm install -g near-cli```

**To Reproduce**
```npm WARN deprecated @ledgerhq/hw-transport-u2f@5.36.0-deprecated: @ledgerhq/hw-transport-u2f is deprecated. Please use @ledgerhq/hw-transport-webusb or @ledgerhq/hw-transport-webhid. https://github.com/LedgerHQ/ledgerjs/blob/master/docs/migrate_webusb.md

changed 307 packages, and audited 308 packages in 10s

25 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities````
type the command : near and show me command not found: near

Have node 14..17.1


**Expected behavior**
neaar command works

- OS:  MacOS 11.6 
- CPU: M1
- RAM: 16gb

**Comment by volovyk-s** [comment]
@ingscjoshua I'm not sure if that is related to the M1 architecture. NEAR CLI should not be affected.
@vgrichina can you please clarify if NEAR CLI works on your M1 machine?

**Comment by volovyk-s** [comment]
Clarified with @vgrichina, works fine with  M1 architecture. Probably the problem is with your $PATH.
If you will have questions, please ask them in [NEAR Discord](https://discord.gg/frF9SeRU).
