### ISSUE TITLE
Error connecting to local node on Debian 11

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-cli#873]
**Describe the bug**
Retrying HTTP request for http://localhost:3030 because of error: FetchError: request to http://localhost:3030/ failed, reason: connect ECONNREFUSED ::1:3030

`Debian 11`

Installed `near cli`
Ran `near-indexer-for-explorer` indexer

![image](https://user-images.githubusercontent.com/4870868/139349028-74353a25-aab9-4691-be72-8f96cde809df.png)

![image](https://user-images.githubusercontent.com/4870868/139349071-8445ed57-0180-494a-857d-868cb99547a3.png)

BLOCKER

**Comment by volovyk-s** [comment]
@evergreen-trading-systems was it working before with NEAR CLI for you?
@khorolets have you seen such an error?

**Comment by khorolets** [comment]
@evergreen-trading-systems could you give us the near-cli command to run, I can't reproduce it on Mac

**Comment by khorolets** [comment]
@volovyk-s 

on Mac

```
$ NEAR_ENV=local near state test.near
Loaded master account test.near key from /Users/khorolets/.near/validator_key.json with public key = ed25519:C7gcTuvcRKZkucxP2ihFKzTGQ6H2C2m5v8i79Lbk96fB
Account test.near
{
  amount: '999999899999150889875000000000000',
  locked: '53503741786773065593486268425715',
  code_hash: '11111111111111111111111111111111',
  storage_usage: 182,
  storage_paid_at: 0,
  block_height: 30295,
  block_hash: 'C9HtmQh9F79WAv2XKnTCh3DzEEAvBZ1Citd2EsNw8wMp',
  formattedAmount: '999,999,899.999150889875'
}

$ near --version
2.1.1
```

**Comment by evergreen-trading-systems** [comment]
This command does not work on Debian 11 - `NEAR_ENV=local near state test.near`

**Comment by volovyk-s** [comment]
I have tried it on Debian 11 and Arch, works fine, probably your machine setup is the reason.
My output:
```bash
serhii@debian11-uni:~/Projects/nearcore$ NEAR_ENV=local near state test.near
Loaded master account test.near key from /home/serhii/.near/validator_key.json with public key = ed25519:3rDbqMNQoaCcPLX86nhozk1EzjKYGydGbUEsjgmji9sw
Account test.near
{
  amount: '1000000000000000000000000000000000',
  locked: '50000970335441577554223744292238',
  code_hash: '11111111111111111111111111111111',
  storage_usage: 182,
  storage_paid_at: 0,
  block_height: 582,
  block_hash: 'CpUN6QPdFkrFUbTJi53SwNyGejWSX4DaV9LcFaZL3Enk',
  formattedAmount: '1,000,000,000'
}

```

Feel free to reopen if if you will be able to reproduce it on other machines.

**Comment by evergreen-trading-systems** [comment]
please reopen and demonstrate that it works via video

**Comment by evergreen-trading-systems** [comment]
Clearly shows it not working

https://user-images.githubusercontent.com/4870868/142728043-e39f0363-234f-404a-8c09-7c2bb9a08adf.mp4
