### ISSUE TITLE
`near validators` shows wrong numbers of seats

### ISSUE THREAD

**Issue by nikurt** [near/near-cli#879]
Run a test network on mocknet (or localnet)

```
$ NEAR_ENV=local near validators current
Loaded master account 1j02-load-test.near key from /home/ubuntu/.near/validator_key.json with public key = ed25519:76NVkDErhbP1LGrSAf5Db6BsFJ6LBw6YVA4BsfTBohmN
Validators (total: 3, seat price: 5,089,930):
.-------------------------------------------------------------------------------------------.
|    Validator Id     |   Stake    | # Seats | % Online | Blocks produced | Blocks expected |
|---------------------|------------|---------|----------|-----------------|-----------------|
| jlk4-load-test.near | 10,179,860 | 1       | 100%     |              89 |              89 |
| 969c-load-test.near | 7,634,895  | 1       | 100%     |              44 |              44 |
| wq7s-load-test.near | 5,089,930  | 0       | 100%     |              45 |              45 |
'-------------------------------------------------------------------------------------------'
```

Expected behavior is to get the numbers of seats: 2 + 1 + 1 = 4
Got numbers of seats: 1 + 1 + 0 = 2

**Comment by volovyk-s** [comment]
@nikurt Have you tried to use RPC Call? I'm wondering if it's on the CLI level.
Also, I'm not sure how to set up a local node with several validators, maybe we can pair and work on it someday.

**Comment by nikurt** [comment]
Good point about the RPC call. Let me try it later and get back to you.

**Comment by nikurt** [comment]
I assume you mean this RPC endpoint: https://docs.near.org/docs/api/rpc/network#validation-status
The response only has stakes and doesn't have seats: [rpc.txt](https://github.com/near/near-cli/files/7584122/rpc.txt)

**Comment by volovyk-s** [comment]
@nikurt This is the function that is getting executed: https://github.com/near/near-cli/blob/7dd821cde1b0875ce61e5ea53847d5efbfef927f/utils/validators-info.js#L17
`result.current_validators.length` is used there.
This is the call to get this result: https://github.com/near/near-cli/blob/7dd821cde1b0875ce61e5ea53847d5efbfef927f/utils/validators-info.js#L11

**Comment by nikurt** [comment]
This issue is already outdated, as 1.23 is going to limit seats to just 1 per validator. Which needs a different code change in `near-cli`.

**Comment by volovyk-s** [comment]
Ok, closing this one then. Should we just delete the `seats` column?

**Comment by nikurt** [comment]
> Delete the `seats` column?

Sounds good.

**Comment by volovyk-s** [comment]
@nikurt I noticed that # of seats can be 0 or 1. Maybe we still need that column. Not sure.
