### ISSUE TITLE
Handle the new seat allocation algorithm in `near proposals` and `near validators`

### ISSUE THREAD

**Issue by nikurt** [near/near-cli#895]
`nearcore 1.23` is scheduled to be released on Dec 13th.
After the protocol upgrade takes place, every validator will have exactly 1 seat, and the seat price calculation will be much simpler.

Seat price can be defined in two ways:
1. minimal staked amount of the active validators.
2. minimal amount that gives a new validator a seat.
I think the second option is more informative in case there are free validator seats.

Would it be possible to make these changes available at roughly the same time as the protocol upgrade happens next week?

**Comment by frol** [comment]
@nikurt Is my assumption correct that we can use `protocol_config` to see the protocol version and use either the old or new seat allocation algorithm?

Where is a minimal amount that gives a new validator a seat is specified? Is it part of the protocol config?

**Comment by nikurt** [comment]
@frol 
Yes, protocol version >= 49 will have the new validator seat allocation algorithm.

```
http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_protocol_config params:='{ "finality": "final" }' | jq '.result.protocol_version'
49
```

The lowest possible price of a seat is `minimum_stake_ratio * total_stake`
https://github.com/near/nearcore/blob/master/chain/epoch_manager/src/validator_selection.rs#L308;L315

The min seat price is also stored in `EpochInfo`: https://github.com/near/nearcore/blob/master/chain/epoch_manager/src/validator_selection.rs#L200

```
% http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_genesis_config | jq '.result.minimum_stake_ratio'     
[
  1,
  6250
]
```

**Comment by frol** [comment]
Just for the reference, the view seat allocation algorithm support in near-cli is blocked on https://github.com/near/near-api-js/issues/744

**Comment by frol** [comment]
@nikurt Why did the `minimum_stake_ratio` option suddenly appear in the genesis config and is not available in the latest protocol config?

```bash
$ http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_protocol_config 'params:={"finality": "final"}' | jq '.result.minimum_stake_ratio'
null

$ http post https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_genesis_config | jq '.result.minimum_stake_ratio'
[
  1,
  6250
]
```

By "suddenly appear" I mean the fact that it clearly did not exist in the initial genesis config (mainnet does not have it):

```bash
$ http post https://rpc.mainnet.near.org jsonrpc=2.0 id=dontcare method=EXPERIMENTAL_genesis_config | jq '.result.minimum_stake_ratio'
null
```

@volovyk-s Just FYI, given that `minimum_stake_ratio` is empty when you query a node without protocol 49 support, the implementation on near-cli side will pass `minimumStakeRatio` as `undefined` into `findSeatPrice`:

```ts
export function findSeatPrice(validators: (CurrentEpochValidatorInfo | NextEpochValidatorInfo)[], maxNumberOfSeats: number, minimumStakeRatio: number[], protocolVersion?: number): BN
```

JS will be fine with that, but if we want to be pedantic, we might think of a better solution (to be honest, I don't think we should spend our cycles on it, but I will let you decide on what to do with this information :smile:)

**Comment by nikurt** [comment]
@EgorKulikov

**Comment by nikurt** [comment]
@frol That field was added to `GenesisConfig` recently: https://github.com/near/nearcore/blame/3bff867fe5b873ed006912bd347fe8bb5d030c28/core/chain-configs/src/genesis_config.rs#L182

**Comment by volovyk-s** [comment]
@frol `near-api-js` should handle this well:
```javascript
function findSeatPrice(validators, maxNumberOfSeats, minimumStakeRatio, protocolVersion) {
    if (protocolVersion && protocolVersion < 49) {
        return findSeatPriceForProtocolBefore49(validators, maxNumberOfSeats);
    }
    if (!minimumStakeRatio) {
        const deprecate = depd_1.default('findSeatPrice(validators, maxNumberOfSeats)');
        deprecate('`use `findSeatPrice(validators, maxNumberOfSeats, minimumStakeRatio)` instead');
        minimumStakeRatio = [1, 6250]; // harcoded minimumStakeRation from 12/7/21
    }
    return findSeatPriceForProtocolAfter49(validators, maxNumberOfSeats, minimumStakeRatio);
}
```
I will not be pedantic this time) This code is basically unreachable and will not fail anyway.
