### ISSUE TITLE
Confirm account deletion

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#900]
_**Describe the bug**_ Account deletion doesn't have confirmation, making it super easy to delete account by accident. Additionally, users don't know that deletion of account won't actually affect other accounts that refer to this account - leaving assets and data owner-less.

 _**To Reproduce**_ Steps to reproduce the behavior: 1\. near delete testmewell.testnet testmewell.testnet

 _**Expected behavior**_ Confirmation that user indeed wants to delete the account. Confirm they understand that if this account owns some assets or data - it will not be transferred to beneficiary. Check if this account owns any tokens or NFTs and provide information that they will not be removed and will be up for grubs by anyone.

 _**User feedback reference**_ See: [https://stackoverflow.com/questions/70313278/a-deleted-testnet-account-gets-fully-restored](https://stackoverflow.com/questions/70313278/a-deleted-testnet-account-gets-fully-restored)

**Comment by MaximusHaximus** [comment]
We can use the `near-contract-helper` to identify a list of contracts that the user _may_ own NFTs or FTs in if they implement NEP-171 and NEP-141.

**NEP-171/NFTs:**
[Contract Helper Route](https://github.com/near/near-contract-helper/blob/master/middleware/indexer.js#L115): POST `{ accountId }` to `/likelyNFTs` 
[Contract method to check ownership](https://nomicon.io/Standards/NonFungibleToken/Enumeration.html#interface): `ft_balance_of` 

**NEP141/FTs:**
[Contract Helper Route](https://github.com/near/near-contract-helper/blob/master/middleware/indexer.js#L151) : POST `{ accountId }` to `/likelyTokens`
[Contract method to check balance](https://nomicon.io/Standards/FungibleToken/Core.html#reference-level-explanation): `nft_tokens_for_owner`

cc: @volovyk-s

**Comment by agileurbanite** [comment]
+1 let's do this
