### ISSUE TITLE
no seed phrase validation when generating key

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-cli#915]
***Describe the bug***
 why invalid phrase can alse generate key-pair?

!<span class="error">[test]</span>([https://user-images.githubusercontent.com/95295094/149619177-3527ccd2-7f22-4cad-9c10-7fe3af8dd592.png](https://user-images.githubusercontent.com/95295094/149619177-3527ccd2-7f22-4cad-9c10-7fe3af8dd592.png))

**Comment by think-in-universe** [comment]
this seems to be an issue to me. should we validate a given BIP319 seed phrase before generating keys with it? 

@thisisjoshford @volovyk-s

**Comment by volovyk-s** [comment]
I'm not sure if we should restrict such a possibility. I have heard several times that people are generating keys from the non-standard set of words or even a single word/string. For example Crossword Puzzle.

**Comment by think-in-universe** [comment]
I agree. I don't think it's a severe issue considering CLI is for developers.

@hanakannzashi do you have any use cases that may bring security concerns?
