### ISSUE TITLE
Using ledger fails if used by another app

### ISSUE THREAD

**Issue by luixo** [near/near-cli#917]
***Describe the bug***
 A command using ledger (with `--useLedgerKey`) fails if ledger itself is being used by another app (say Firefox).
 The error you get in this case doesn't help much:
 ```
 TypeError: cannot open device with path IOService:/AppleARMPE/arm-io/AppleT600xIO/usb-drd2@2280000/AppleT6000USBXHCI@02000000/usb-drd2-port-hs@02100000/USB2.0 Hub@02100000/AppleUSB20Hub@02100000/AppleUSB20HubPort@02110000/Nano S@02110000/Nano S@0/AppleUserUSBHostHIDDevice
 at new HID (/Users/luixo/.nvm/versions/node/v14.18.2/lib/node_modules/near-cli/node_modules/node-hid/nodehid.js:49:17)
 at /Users/luixo/.nvm/versions/node/v14.18.2/lib/node_modules/near-cli/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:76:45
 at processTicksAndRejections (internal/process/task_queues.js:95:5)
 at async useLedgerSigner (/Users/luixo/.nvm/versions/node/v14.18.2/lib/node_modules/near-cli/middleware/ledger.js:15:23)
 at async Promise.all (index 1)
 ```

***To Reproduce***
 1\. Open your ledger-connected wallet account with Firefox (optionally, open Ledger Live)
 1\. Wait until ledger is "authorized"
 1\. Call `near generate-key --useLedgerKey`, see error
 1\. Close Firefox / close Ledger Live / reconnect device
 1\. Call `near generate-key --useLedgerKey` again, see prompt on device

***Expected behavior***
 Proper error description (e.g. "try to close apps, reconnect device")

***Desktop (please complete the following information):***

*   OS: MacOS Monterey
*   Version: near 3.1.0

**Comment by luixo** [comment]
Did that got fixed?

**Comment by gagdiez** [comment]
we dropped ledger support, as this tool is not being actively maintained. We recommend moving to near-cli-rs, which is actively being maintained by DevHub
