### ISSUE TITLE
Experiment geo capture on testnet

### ISSUE THREAD

**Issue by TiffanyGYJ** [near/near-cli#956]
**Is your feature request related to a problem? Please describe.**
In order to better understand the geographical distribution of our developers, we would like to capture geo information via CLI testnet, likely via an analysis of IP address. 

**Describe the solution you'd like**
Turn on ip=true on CLI.

**Describe alternatives you've considered**
Change CLI tracking to  server side. 

**Additional context**
Request from management.

**Comment by igorkauf** [comment]
@volovyk-s if the change requires only changing IP to true on CLI, I hope it's smth that is quick to do. Thanks
