### ISSUE TITLE
Having called my smart contract code several times from a React front-end, I'm getting this error severally

### ISSUE THREAD

**Issue by morarafrank** [near/near-cli#993]
"Smart contract panicked: panicked at 'Failed to deserialize input from JSON.: Error("missing field `first_candidate`", line: 1, column: 2)', src/lib.rs:114:1"}}

**Comment by willemneal** [comment]
This error is saying that the JSON sent to the contract was missing a required key here `first_candidate`.  Can you share your full command?

**Comment by morarafrank** [comment]
near call abc.testnet get_first_candidate abc.testnet

**Comment by willemneal** [comment]
You need to serialize the call in JSON:

```

near call abc.testnet get_first_candidate '{"first_candidate": "abc.testnet" }'

```

Currently you are pass `abc.testnet` as the whole argument.

**Comment by morarafrank** [comment]
Thanks @willemneal . It worked. Seems I was not passing the whole argument.
